import Image from "next/image";
import "../styles/globals.css";
import Footer from "../ui/Footer";
import HeaderComponent from "../ui/HeaderComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head />
      <body>
        <HeaderComponent />
        <div className="md:pt-[10rem] pt-[5rem] ">{children}</div>
        <Image
          src="https://picsum.photos/3419/1195"
          alt="/"
          width="1000"
          height="1000"
        ></Image>
        <Footer />
      </body>
    </html>
  );
}
